### ISSUE TITLE
by user 

### ISSUE THREAD

**Issue by Arwa200** [p3lli/Tweets-to-CSV#3]
I'm trying to run the program but stoped here when type by user, got me No command found even when writing a real user name
![Screen Shot 2019-11-07 at 10 23 55 AM](https://user-images.githubusercontent.com/42224049/68368558-63649d00-0149-11ea-815d-78e286c437f5.png)

can you please give an examples of using by user and keyword with real names, i just want to check if write it correctly 

another two questions 
is this project could be applied for likes? 
this is not a real time or auto saver tweets right? 

Thank you

**Comment by p3lli** [comment]
Hi, and thank you for using my little project.

You can download tweet from user "foo" and storing them in a .csv using the command:
`python main.py by-user foo .`

Reading `python-twitter` documentation I did not manage to find a fast way to gather number of likes per tweet, I'm sorry.

This is not a real time or autosaver.

**Comment by Arwa200** [comment]
hi again 
when I'm trying to run the previous command, I got no result, its showing these options -h, -a, -c and -v 

I run the following command: python main.py by-user Arwa200

![Screen Shot 2019-11-26 at 6 21 56 PM](https://user-images.githubusercontent.com/42224049/69647444-8d3f1e80-107a-11ea-9a37-8038201025a6.png)

Thank you

**Comment by p3lli** [comment]
Hi Arwa200,
forgive me, I have not answered you yet.

It is very simple, you did not specify your destination directory for the .csv
Try: python main.py by-user Arwa200 .

Edit: have a look to the Usage section in README

**Comment by Arwa200** [comment]
Hi, Never mind
Thank you for help, I will try your solution for later and get to you as soon as possible
Thank You So Much..
