### ISSUE TITLE
Problem by downloading tweets by users list

### ISSUE THREAD

**Issue by benedetta25** [p3lli/Tweets-to-CSV#5]
Hi there. 
I have used the script and works perfectly. However, when I run the command 
` main.py by-users-list keywords_list.txt directory `
it correcly downloads the tweet by users but it also includes the tweets created by my twitter user. Some hints?

**Comment by p3lli** [comment]
Hi, thank you for your feedback!
This behaviour is caused by the presence of a trailing newline in `keywords_list.txt`
My team and I are working on a way to avoid reading empty username.

Stay tuned
